# Generated by Django 4.1.1 on 2022-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dateAdded',
            field=models.DateTimeField(default=None, verbose_name='Date added '),
        ),
        migrations.AddField(
            model_name='todolist',
            name='due',
            field=models.DateTimeField(default=None, verbose_name='Due date to complete'),
        ),
    ]
